- hosts: localhost
  tasks:
     - name: Associate tag with a component (format=maven only)
       nxrm_tag_associate:
         repo_name: "{{ repo_name }}"
         tag_name: "{{ tag_name }}"
         groupId: "{{ group_id }}"
         artifactId: "{{ artifact_id }}"
         version: "{{ version }}"
         format: "{{ format }}"
       register: op

     - debug:
         var: op

